name: CI

on:
    pull_request:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Lint
              run: yarn lint:prettier

    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run Tests
              run: yarn test
